apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        image: system:1.0-SNAPSHOT
        env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: GROUP_ID
          value: "system-client-group"
        ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory-container
        image: inventory:1.0-SNAPSHOT
        env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: GROUP_ID_PREFIX
          value: "system-properties"
        ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-deployment
  labels:
    app: job
spec:
  selector:
    matchLabels:
      app: job
  template:
    metadata:
      labels:
        app: job
    spec:
      containers:
      - name: job-container
        image: job:1.0-SNAPSHOT
        env:
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: GROUP_ID_PREFIX
          value: job
        ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  labels:
    app: bff
spec:
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
      - name: bff-container
        image: bff:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  type: NodePort
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32000
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  type: NodePort
  selector:
    app: job
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32100
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  type: NodePort
  selector:
    app: bff
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32200
